---
- name: Install dependencies
  apt:
    name:
      - python-httplib2
      - python-apt
      - curl
      - ntp
      - apt-transport-https
    state: present
    update_cache: yes
    cache_valid_time: 3600
  register: apt_result
  until: apt-result | success
  retries: 2
  delay: 5

- name: Install Telegraf
  apt:
    name: telegraf
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  register: apt_result
  until: apt_result is success
  retries: 2
  delay: 5
  when: telegraf_install_url is not defined or telegraf_install_url == None

